sources:
  - name: axios
    url: https://api.axios.com/feed/
  - name: maariv-tech
    url: https://www.maariv.co.il/rss/rssfeedstechnologeya
  - name: maariv
    url: https://www.maariv.co.il/rss/rssfeedsmivzakichadashot
    enabled: false
    block_words:
      - האח הגדול, ממש לא
  - name: phoronix
    url: https://www.phoronix.com/rss.php
  - name: newsru
    url: https://www.newsru.co.il/il/www/news/big
    block_words:
      - футбол, дзюдо, гран-при, чемпионат, прыжки с шестом
  - name: Techmeme
    url: https://www.techmeme.com/feed.xml
    #enabled: false
  - name: Mivzakim
    url: https://rss.mivzakim.net/rss/category/1
    source_filter: Ynet  # Filter by source name (e.g., "N12"), null for all sources
    enabled: false
  - name: The Register AI
    url: https://www.theregister.com/software/ai_ml/headlines.atom
  - name: AI News
    url: https://www.artificialintelligence-news.com/feed/
  - name: Wired
    url: https://www.wired.com/feed/tag/ai/latest/rss
    enabled: false
  - name: Ynet
    url: https://www.ynet.co.il/Integration/StoryRss1854.xml
    block_words:
      - מטולה, אצבע הגליל, משגב עם, אצבע הגליל, מרגליות, במנרה
  - name: ynet - דיגיטל
    url: https://www.ynet.co.il/Integration/StoryRss544.xml
  - name: The Decoder
    url: https://the-decoder.com/feed/
  - name: Guardian AI
    url: https://www.theguardian.com/technology/artificialintelligenceai/rss
  - name: The Next Web Neural
    url: https://thenextweb.com/neural/feed
  - name: HackerNoon AI
    url: https://hackernoon.com/tagged/ai/feed
    min_interval: 3600
    #enabled: false
  - name: SiliconAngle AI
    url: https://siliconangle.com/category/ai/feed
  - name: Futurism AI
    url: https://futurism.com/categories/ai-artificial-intelligence/feed
  - name: Phys.org ML
    url: https://phys.org/rss-feed/technology-news/machine-learning-ai/
    enabled: false
  - name: The New Stack
    url: https://thenewstack.io/feed
  - name: RedHat Next
    url: https://next.redhat.com/feed/
  - name: RedHat Dev
    url: https://developers.redhat.com/blog/feed
    har: developers.redhat.com.har
  - name: arXiv AI
    url: https://rss.arxiv.org/atom/cs.ai+cs.lg

settings:
  max_items: 10
  poll_interval: 60
  tts_volume_adjust: -10
  block_words_file: ~/cmnd/block_words.txt
  replace:
    - pattern: '^\w+: '
    - pattern: '\s*\([^)]+\)\s*$'
