sources:
  - name: axios
    url: https://api.axios.com/feed/
  - name: techmeme
    url: https://www.techmeme.com/feed.xml
  - name: The Register AI
    url: https://www.theregister.com/software/ai_ml/headlines.atom
  - name: ai news
    url: https://www.artificialintelligence-news.com/feed/
  - name: the decoder
    url: https://the-decoder.com/feed/
  - name: guardian ai
    url: https://www.theguardian.com/technology/artificialintelligenceai/rss
  - name: the next web neural
    url: https://thenextweb.com/neural/feed
  - name: hackernoon ai
    url: https://hackernoon.com/tagged/ai/feed
    min_interval: 3600
  - name: siliconangle ai
    url: https://siliconangle.com/category/ai/feed
  - name: futurism ai
    url: https://futurism.com/categories/ai-artificial-intelligence/feed
  - name: the new stack
    url: https://thenewstack.io/feed
  - name: nvidia
    url: https://blogs.nvidia.com/feed/
  - name: redhat next
    url: https://next.redhat.com/feed/
  - name: redhat dev
    url: https://developers.redhat.com/blog/feed
    har: developers.redhat.com.har
    #enabled: false
  - name: arxiv ai
    url: https://rss.arxiv.org/atom/cs.ai+cs.lg
  - name: wired
    url: https://www.wired.com/feed/tag/ai/latest/rss
    enabled: false
  - name: phys.org ml
    url: https://phys.org/rss-feed/technology-news/machine-learning-ai/
    enabled: false

settings:
  max_items: 10
  poll_interval: 60
  tts_volume_adjust: -10
  tts_voices: [Achernar, Achird, Algenib, Algieba, Alnilam,
    Aoede, Autonoe, Callirrhoe, Charon, Despina,
    Enceladus, Erinome, Fenrir, Gacrux, Iapetus,
    Kore, Laomedeia, Leda, Orus, Puck,
    Pulcherrima, Rasalgethi, Sadachbia, Sadaltager,
    Schedar, Sulafat, Umbriel, Vindemiatrix, Zephyr,
    Zubenelgenubi]
  tts_piper_model: ~/.local/share/piper-voices/en_US-lessac-medium.onnx
  replace:
    - pattern: '^\w+: '
    - pattern: '\s*\([^)]+\)\s*$'
